services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.php
    image: custom_php
    container_name: casaweb_app
    volumes:
      - ./public:/var/www/html
      - ./:/var/www/project
    depends_on:
      - database
    working_dir: /var/www/project
    networks:
      - casaweb_network

  nginx:
    image: nginx:1.29.1
    container_name: casaweb_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - casaweb_network

  database:
    image: mysql:8.4.6
    container_name: casaweb_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: casaweb
      MYSQL_USER: casaweb
      MYSQL_PASSWORD: casaweb
    volumes:
      - ./.docker/mysql_data:/var/lib/mysql
    networks:
      - casaweb_network

networks:
  casaweb_network:
    driver: bridge
    name: casaweb_network
